update url

diff --git a/base/deployments/gitlab/healthcheck.yaml b/base/deployments/gitlab/healthcheck.yaml
--- a/base/deployments/gitlab/healthcheck.yaml
+++ b/base/deployments/gitlab/healthcheck.yaml
@@ -25,24 +25,20 @@ spec:
             - -c
             - |
               echo "Performing GitLab liveness check at $(date -Iseconds)..."
-              
-              ## Use a variable for the target URL for easier management
-              #TARGET_URL="https://httphin.org/status/200"
-              #
-              ## Run the curl command and capture the HTTP status code.
-              ## The -s flag makes the output silent.
-              ## The -w flag writes the status code to stdout.
-              #STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$TARGET_URL")
 
-              ## Check the status code and log the result to stdout.
-              ## This can then be captured by the cron job's logs in GKE.
-              #if [ "$STATUS_CODE" -eq 200 ]; then
-              #  echo "Liveness check SUCCESS. Status code: $STATUS_CODE"
-              #  exit 0
-              #else
-              #  echo "Liveness check FAILED. Status code: $STATUS_CODE" 1>&2
-              #  exit 1
-              #fi
+              TARGET_URL="https://www.example.com"
+              
+              # Run the curl command and capture the HTTP status code.
+              STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$TARGET_URL")
+
+              # Check the status code and log the result to stdout.
+              if [ "$STATUS_CODE" -eq 200 ]; then
+                echo "Liveness check SUCCESS. Status code: $STATUS_CODE"
+                exit 0
+              else
+                echo "Liveness check FAILED. Status code: $STATUS_CODE" 1>&2
+                exit 1
+              fi
               sleep 30
             resources:
               requests:
